#!/usr/bin/env bash
# Display information relating to subdomains of a domain

# Function to display information about a subdomain
function display_subdomain_info() {
  local domain="$1"
  local subdomain="$2"

  record_type="$(dig +noall +answer "$subdomain.$domain" | awk '{print $4}')"
  destination="$(dig +short "$subdomain.$domain")"

  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [[ $# -eq 2 ]]; then
  domain="$1"
  subdomain="$2"

  display_subdomain_info "$domain" "$subdomain"
else
  domain="$1"
  subdomains=("www" "lb-01" "web-01" "web-02")

  for subdomain in "${subdomains[@]}"; do
    display_subdomain_info "$domain" "$subdomain"
  done
fi
