#!/usr/bin/env bash
# A script to install Nginx on web-01 server

sudo apt-get update
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www
touch /var/www/html/index.html
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
