#!/usr/bin/env bash
# A script to install Nginx on web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
touch /var/www/html/index.html
sudo chmod 666 /var/www/html/*.html
echo "Hello World!" > /var/www/html/index.html
sudo nginx -s reload
