#!/usr/bin/env bash
# Install load balancer

# Install HAProxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

# Configure HAProxy
sudo chown -R ubuntu /etc/haproxy

echo "
frontend web-frontend
  bind *:80
  mode http
  default_backend myservers

backend myservers
  balance roundrobin
  mode http
  server 241794-web-01 100.26.241.94:80 check
  server 241794-web-02 35.168.1.10:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
