#!/usr/bin/env bash
# a Bash script that:
# * Creates the file /var/run/myscript.pid containing its PID
# * Displays To infinity and beyond indefinitely
# * Displays I hate the kill command when receiving a SIGTERM signal
# * Displays Y U no love me?! when receiving a SIGINT signal
# * Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"
echo "$$" > "$file"

clean() {
	echo "I hate the kill command"
	rm -rf "$file"
	exit 0
}

love_me() {
	echo "Y U no love me?!"
}

trap love_me SIGINT
trap clean SIGQUIT SIGTERM

while true;
do
	echo "To infinity and beyond"
done
