#!/usr/bin/env bash
# The script loops from 1 to 10 and:
# displays "bad luck" for the fourth loop iteration
# displays "good luck" for the fourth loop iteration
# displays "Best School" for the other loop iterations

counter=1
Best="Best School"

while ((counter <= 10));
do
	if ((counter == 4))
	then
		echo "bad luck"
	elif ((counter == 8))
	then
		echo "good luck"
	else
		echo "$Best"
	fi

	((counter++))
done
