#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and:
# 	* displays 4 and then "bad luck from China" for the 4th loop iteration
# 	* displays 9 and then "bad luck from Japan" for the 9th loop iteration
# 	* displays 17 and then "bad luck from Italy" for the 17th loop iteration
######################################################################

counter=1
China="bad luck from China"
Japan="bad luck from Japan"
Italy="bad luck from Italy"

while ((counter <= 20));
do
	echo "$counter";

	if ((counter == 4))
	then
		echo "$China";
	elif ((counter == 9))
	then
		echo "$Japan";
	elif ((counter == 17))
	then
		echo "$Italy";
	fi

	((counter++))
done;