#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
#  * display hours from 0 to 12
#  * display minutes from 1 to 59
# Requirements:
#  * You must use the while loop (for and until are forbidden)
######################################################################

hours=0

while ((hours<=12)); do
	minutes=1
	echo "Hour: $hours"

	while ((minutes <= 59)); do
		echo "$minutes"
		((minutes++))
	done

	((hours++))
done