#!/usr/bin/env bash
#######################################################################
# A Bash script that gives you information about the school file.
# Requirements:
#  * You must use if and, else (case is forbidden)
#  * Your Bash script should check if the file exists and print:
# 	 * if the file exists: school file exists
# 	 * if the file does not exist: school file does not exist
#  * If the file exists, print:
# 	 * if the file is empty: school file is empty
# 	 * if the file is not empty: school file is not empty
# 	 * if the file is a regular file: school is a regular file
# 	 * if the file is not a regular file: (nothing)
#######################################################################

file="school"

#test if file exists
if [[ -e "$file" ]];
then
	echo "$file file exists"

	#test if file is empty
	if [[ -s "$file" ]];
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	# test if file is a regular file
	if [[ -f "$file" ]];
	then
		echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi
