#!/usr/bin/env bash
# run nginx as user 'nginx' on port 8080
sudo chown -R nginx:nginx /var/run/nginx.pid
sudo chown -R nginx:nginx /var/cache/nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /etc/nginx/conf.d
sed -i "s/^#*user www-data;/user nginx nginx;/" /etc/nginx/nginx.conf
service nginx restart
