#!/usr/bin/env bash
# run nginx as user 'nginx' on port 8080
sudo chown -R nginx:nginx /etc/nginx/conf.d
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sed -i "s/^#*user www-data;/user nginx nginx;/" /etc/nginx/nginx.conf
service nginx restart
