#!/usr/bin/env bash
# run nginx as user 'nginx' on port 8080
sudo chown -R nginx:nginx /usr/sbin/nginx
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod 755 /etc/nginx/nginx.conf
sed -i "s/^#*user www-data;/user nginx nginx;/" /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
