#!/usr/bin/env bash
# run nginx as user 'nginx' on port 8080
pkill -f apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx nginx
sudo service nginx start
