#!/usr/bin/env bash
# A Bash script that uses ssh to connect to your server using the private key `~/.ssh/school` with the user `ubuntu`.

ssh-copy-id -i ~/.ssh/school ubuntu@18.206.233.207
ssh ubuntu@18.206.233.207
